[package]
name = "anti_sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.0"

[dependencies.windows]
version = "0.48.0"
features = [
    "Win32_System_SystemInformation",
    "Win32_System_Registry",
    "Win32_Foundation",
]
